### PR TITLE
Support snap installations

### PR DESCRIPTION
**Pull request by Chithrak07**

### CODE REVIEW

**Comment by dale-c-anderson** [comment]
@Chithrak07 I'm not sure what I should be reviewing here. I cant get molecule to pass for any OS version, this seems really incomplete. Are you testing the role elsewhere? Also, this PR is merging into master; should we not be merging into the add-automated-tests branch, since that's where this was branched from?

**Comment by Chithrak07** [comment]
@dale-c-anderson : Oh, this is not about molecule tests. I thought we decided to let it sit on the table.

When we tested the instance creations against u20, this role was not getting through because certbot requires 'snap' to get it installed. So I have removed some of the previous code and is now using snap to install certbot.

**Comment by dale-c-anderson** [comment]
OK fair enough, but if we're ignoring molecule, then why are we branching from the molecule branch? Wouldn't it make more sense to branch from master? We can't very well merge molecule tests into master if they're not working.

**Comment by Chithrak07** [comment]
> OK fair enough, but if we're ignoring molecule, then why are we branching from the molecule branch? Wouldn't it make more sense to branch from master? We can't very well merge molecule tests into master if they're not working.

Right, will create a new MR.

**Pull request closed without merging**
